### ISSUE TITLE
Add methods for finding all the Kings in a House

### ISSUE THREAD

**Issue by kyleoliveira** [FranklinTOliveira/RoyalsOfBritain#4]
# To Do
Update the `KingsService` and `KingsRepository` with methods for getting all the Kings for a given House. The methods you'll need to add are:
* `List<King> findByHouse_Name(String houseName, Sort sort);` in `KingsRepository`
* `public List<King> findByHouse_Name(String houseName)` in `KingsService`

# Notes
* You may also need to define attributes for the associations between the two entities. `King#house` would be a `@OneToOne` and `House#kings` would be a `@OneToMany`
* Be sure to do the work on a new branch
* When you're done, push the branch to GitHub and use it to make a new Pull Request and tag me as an **Assignee**

**Comment by FranklinTOliveira** [comment]
Resolved by #7
