### ISSUE TITLE
Generate the table of kings on the house page based on the Kings of that House

### ISSUE THREAD

**Issue by kyleoliveira** [FranklinTOliveira/RoyalsOfBritain#5]
# To Do
Add a new Wicket component that'll generate the table of Kings on the `HouseInformationPage`.
You can do this with a `RepeatingView` similarly to how the `HousesDropdown` works, though there are certainly other approaches that will work as well. You'll need to use `Label`s to fill in the cells of the table.

After adding the new component, use that component on the `HouseInformationPage`.

# Notes
* Be sure to do the work on a new branch
* When you're done, push the branch to GitHub and use it to make a new Pull Request and tag me as an **Assignee**

**Comment by FranklinTOliveira** [comment]
Success!
